# Generated by Django 3.0.3 on 2020-04-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_historical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyhistorical',
            table='daily_historical',
        ),
    ]
